apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ip-whitelister.fullname" . }}
  labels:
    {{- include "ip-whitelister.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | nindent 4 }}
