name: package helm chart

on:
  pull_request:
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'
  push:
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      -
        name: Test Helm chart
        run: helm lint helm/ip-whitelister
      -
        name: Template Helm chart
        run: helm template helm/ip-whitelister
      -
        # if: github.ref == 'refs/heads/main' 
        if: ${{ github.event.tag }}
        name: Package Helm chart
        run: helm package helm/ip-whitelister && mv *.tgz helm-chart-`ls -1 *.tgz`
      -
        # if: github.ref == 'refs/heads/main' 
        if: ${{ github.event.tag }}
        name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: test
          draft: true
          prerelease: false
          files: |
            *.tgz
