name: package helm chart

on:
  pull_request:
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'
  release:
    types: [created]
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'
    branches:
      - main
  push:
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      -
        name: Test Helm chart
        run: helm lint helm/ip-whitelister
      -
        name: Template Helm chart
        run: helm template helm/ip-whitelister
      -
        # if: github.ref == 'refs/heads/main' 
        if: ${{ github.event.release }}
        name: Package Helm chart
        run: helm package helm/ip-whitelister && mv *.tgz helm-chart-`ls -1 *.tgz`
      -
        # # if: github.ref == 'refs/heads/main' 
        # if: ${{ github.event.release }}
        # name: Create release
        # uses: "marvinpinto/action-automatic-releases@latest"
        # with:
        #   repo_token: "${{ secrets.GITHUB_TOKEN }}"
        #   draft: true
        #   prerelease: false
        #   title: Helm chart updated
        #   files: |
        #     *.tgz
        # # if: github.ref == 'refs/heads/main'
        name: Create release
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
